INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (	1,1,'contacts','last_name','Фамилия','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','first_name','Имя','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','midle_name','Отчество','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','sex','Пол','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','education','Образование','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','date_birsday','Дата рождения','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','married','Семейное состояние','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','family_count','Колличество членов семьи','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_tax','Идентификационный код','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','pwd','Пароль','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','login_name','Логин','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_name','Last name','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','first_name','First name','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','midle_name','Midle name','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','sex','Sex','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','education','Education','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','date_birsday','Date birsday','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','married','Married','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','family_count','Family count','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_tax','Identification code','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','pwd','Password','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','login_name','Login name','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_name','Прізвище','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','first_name','Ім`я','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','midle_name','По батькові','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','sex','Стать','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','education','Освіта','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_tax','Ідентифікаційний код','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','pwd','Пароль до системи','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','login_name','Логін до системи','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created_by','Хто додав запис','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_contact','ИД позичальника','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_row','ИД запису','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated','Дата модифікування запису','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated_by','Хто модифікувв запис','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created','Дата вставки запису','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created_by','Кто вставил запись','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_contact','ИД заемщика','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_row','ИД записи','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated','Дата модификации записи','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created','Date created','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated_by','Кто модифицировал запись','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created_by','Who created','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_contact','Id contact','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_row','Id row','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated','Date last updated','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated_by','Who last updated','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created','Дата додавання запису','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','residency','Residency','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','residency','Резидентність','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','residency','Резидентность','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','citizenship','Сitizenship','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','citizenship','Громадянство','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','citizenship','Гражданство','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_family','income family','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_family','Дохід родини за місяць','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_family','Семейный доход за месяц','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_monthly','income person','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_monthly','Свій дохід за місяць','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_monthly','Личный доход за месяц','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','employment_type','employment type','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','employment_type','Тип зайнятості','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','employment_type','Тип занятости','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_place','Work place','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_place','Місце роботи','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_place','Место работы','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_position','Work_position','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_position','Посада','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_position','Должность','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','address_type','Address type','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','address_type','Тип адреси','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','address_type','Тип Адреса','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','area','Area','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','area','Область','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','area','Область','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city','Сity','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city','Населенний пункт','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city','Населенный пункт','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','corp','Housing','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','corp','Корпус','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','corp','Корпус','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','district','District','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','district','Район','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','district','Район','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','flat','Flat','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','flat','Квартира','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','flat','Квартира','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','house','House','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','house','Будинок','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','house','Дом','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','post_index','Post_index','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','post_index','Поштовий індекс','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','post_index','Почтовый индекс','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street','Street','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street','Вулиця','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street','Улица','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street_type','Street_type','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street_type','Тип вулиці','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street_type','Тип улицы','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','date_doc_given','date document given','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','date_doc_given','Дата видачі документа','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','date_doc_given','Дата выдачи документа','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_given','issued document','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_given','Ким винаний','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_given','Кем выдан','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_number','Document number','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_number','Номер документу','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_number','Номер документа','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_seria','Document seria','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_seria','Серія документу','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_seria','Серия документа','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_type','Document type','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_type','Тип документу','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_type','Тип документа','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_number','Phone number','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_number','Номер телефону','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_number','Номер телефона','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name','Login social network','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name','Логін у соц.мережі','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name','Логин в соц.сети','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_type','Phone type','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_type','Тип телефонного номеру','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_type','Тип телефонного номера','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name_type','social network','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name_type','Соціальна мережа','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name_type','Социальная сеть','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','date_birsday','Дата народження','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','married','Сімейний стан','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','family_count','Кількість членів родини','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city_type','Тип населенного пункту','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city_type','Тип населенного пункта','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city_type','Type of settlement','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','use_for_correspondence','Использовать для корреспонденц','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','use_for_correspondence','Використовувати для кореспонд.','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','use_for_correspondence','use for correspondence','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','use_for_sms','Использовать для СМС валидации','РУС');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','use_for_sms','Використовувать для СМС валіда','УКР');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','use_for_sms','use for SMS','ENG');

INSERT INTO icredit.contacts_caption ( table_name, field_name, caption_name, localisation)
VALUES ( 'contacts', 'localisation', 'language', 'ENG');

INSERT INTO icredit.contacts_caption ( table_name, field_name, caption_name, localisation)
VALUES ( 'contacts', 'localisation', 'Мова спілкування', 'УКР');

INSERT INTO icredit.contacts_caption ( table_name, field_name, caption_name, localisation)
VALUES ( 'contacts', 'localisation', 'Язык общения', 'РУС');

