INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (	1,1,'contacts','last_name','Фамилия','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','first_name','Имя','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','midle_name','Отчество','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','sex','Пол','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','education','Образование','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','date_birsday','Дата рождения','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','married','Семейное состояние','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','family_count','Колличество членов семьи','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_tax','Идентификационный код','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','pwd','Пароль','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','login_name','Логин','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_name','Last name','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','first_name','First name','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','midle_name','Midle name','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','sex','Sex','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','education','Education','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','date_birsday','Date birsday','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','married','Married','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','family_count','Family count','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_tax','Identification code','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','pwd','Password','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','login_name','Login name','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_name','Прізвище','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','first_name','Ім`я','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','midle_name','По батькові','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','sex','Стать','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','education','Освіта','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_tax','Ідентифікаційний код','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','pwd','Пароль до системи','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_pwd','login_name','Логін до системи','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created_by','Хто додав запис','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_contact','ИД позичальника','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_row','ИД запису','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated','Дата модифікування запису','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated_by','Хто модифікувв запис','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created','Дата вставки запису','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created_by','Кто вставил запись','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_contact','ИД заемщика','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_row','ИД записи','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated','Дата модификации записи','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created','Date created','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated_by','Кто модифицировал запись','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created_by','Who created','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_contact','Id contact','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','id_row','Id row','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated','Date last updated','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','last_updated_by','Who last updated','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','created','Дата додавання запису','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','residency','Residency','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','residency','Резидентність','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','residency','Резидентность','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','citizenship','Сitizenship','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','citizenship','Громадянство','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','citizenship','Гражданство','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_family','income family','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_family','Дохід родини за місяць','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_family','Семейный доход за месяц','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_monthly','income person','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_monthly','Свій дохід за місяць','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','income_monthly','Личный доход за месяц','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','employment_type','employment type','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','employment_type','Тип зайнятості','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','employment_type','Тип занятости','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_place','Work place','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_place','Місце роботи','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_place','Место работы','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_position','Work_position','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_position','Посада','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','work_position','Должность','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','address_type','Address type','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','address_type','Тип адреси','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','address_type','Тип Адреса','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','area','Area','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','area','Область','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','area','Область','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city','Сity','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city','Населенний пункт','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city','Населенный пункт','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','corp','Housing','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','corp','Корпус','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','corp','Корпус','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','district','District','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','district','Район','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','district','Район','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','flat','Flat','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','flat','Квартира','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','flat','Квартира','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','house','House','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','house','Будинок','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','house','Дом','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','post_index','Post_index','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','post_index','Поштовий індекс','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','post_index','Почтовый индекс','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street','Street','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street','Вулиця','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street','Улица','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street_type','Street_type','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street_type','Тип вулиці','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','street_type','Тип улицы','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','date_doc_given','date document given','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','date_doc_given','Дата видачі документа','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','date_doc_given','Дата выдачи документа','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_given','issued document','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_given','Ким винаний','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_given','Кем выдан','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_number','Document number','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_number','Номер документу','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_number','Номер документа','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_seria','Document seria','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_seria','Серія документу','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_seria','Серия документа','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_type','Document type','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_type','Тип документу','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_documents','doc_type','Тип документа','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_number','Phone number','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_number','Номер телефону','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_number','Номер телефона','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name','Login social network','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name','Логін у соц.мережі','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name','Логин в соц.сети','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_type','Phone type','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_type','Тип телефонного номеру','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','phone_type','Тип телефонного номера','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name_type','social network','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name_type','Соціальна мережа','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','name_type','Социальная сеть','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','date_birsday','Дата народження','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','married','Сімейний стан','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts','family_count','Кількість членів родини','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city_type','Тип населенного пункту','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city_type','Тип населенного пункта','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_adress','city_type','Type of settlement','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','use_for_correspondence','Использовать для корреспонденц','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','use_for_correspondence','Використовувати для кореспонд.','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_www','use_for_correspondence','use for correspondence','ENG');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','use_for_sms','Использовать для СМС валидации','RUS');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','use_for_sms','Використовувать для СМС валіда','UKR');
INSERT INTO icredit.contacts_caption ("created_by", "last_updated_by", "table_name", "field_name", "caption_name", "localisation") VALUES (1,1,'contacts_phones','use_for_sms','use for SMS','ENG');

INSERT INTO icredit.contacts_caption ( table_name, field_name, caption_name, localisation)
VALUES ( 'contacts', 'localisation', 'language', 'ENG');

INSERT INTO icredit.contacts_caption ( table_name, field_name, caption_name, localisation)
VALUES ( 'contacts', 'localisation', 'Мова спілкування', 'UKR');

INSERT INTO icredit.contacts_caption ( table_name, field_name, caption_name, localisation)
VALUES ( 'contacts', 'localisation', 'Язык общения', 'RUS');

