INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','first_name',1,1,1,1,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','last_name',1,1,2,2,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','midle_name',1,1,3,3,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','id_tax',1,1,4,4,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','date_birsday',1,1,5,5,'calendar','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','sex',1,1,6,6,'radio','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','residency',1,1,7,7,'radio','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','citizenship',1,1,8,8,'radio','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','married',1,2,1,9,'radio','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','family_count',1,2,2,10,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','income_family',1,2,3,11,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','income_monthly',1,2,4,12,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','education',1,3,1,13,'lov','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','employment_type',1,4,1,14,'lov','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','work_place',1,4,2,15,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts','work_position',1,4,3,16,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','address_type',2,5,0,1,'lov','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','area',2,5,1,2,'lov','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','city',2,5,4,3,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','corp',2,5,8,4,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','district',2,5,2,5,'lov','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','flat',2,5,10,6,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','house',2,5,9,7,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','post_index',2,5,7,8,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','street',2,5,6,9,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','street_type',2,5,5,10,'lov','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_documents','date_doc_given',3,6,5,1,'calendar','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_documents','doc_given',3,6,4,2,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_documents','doc_number',3,6,3,3,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_documents','doc_seria',3,6,2,4,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_documents','doc_type',3,6,1,5,'lov','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_phones','phone_number',4,7,2,1,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_phones','phone_type',4,7,1,2,'lov','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_pwd','login_name',5,9,1,1,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_pwd','pwd',5,2,8,2,'simple','FALSE','TRUE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_www','name',4,8,2,1,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_www','name_type',4,8,1,2,'simple','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_adress','city_type',1,5,3,13,'lov','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_phones','use_for_sms',4,7,1,3,'lov','TRUE','FALSE');
INSERT INTO icredit.contacts_access ("id_role", "table_name", "field_name", "page_number", "group_number", "group_sorting", "sorting", "field_view_type", "visible", "ro") values (1,'contacts_www','use_for_correspondence',1,8,3,3,'lov','TRUE','TRUE');
 INSERT INTO icredit.contacts_access (id_role, table_name, field_name, page_number, group_number, group_sorting, sorting, field_view_type, visible, ro)
VALUES ( 1, 'contacts_documents', 'contacts_documents', 3, 6, 1, 0, 'table', true, false);

INSERT INTO icredit.contacts_access ( id_role, table_name, field_name, page_number, group_number, group_sorting, sorting, field_view_type, visible, ro)
VALUES ( 1, 'contacts_phones', 'contacts_phones', 4, 7, 1, 0, 'table', true, false);

INSERT INTO icredit.contacts_access ( id_role, table_name, field_name, page_number, group_number, group_sorting, sorting, field_view_type, visible, ro)
VALUES ( 1, 'contacts_www', 'contacts_www', 4, 8, 1, 0, 'table', true, false);

INSERT INTO icredit.contacts_access ( id_role, table_name, field_name, page_number, group_number, group_sorting, sorting, field_view_type, visible, ro)
VALUES ( 1, 'contacts_adress', 'contacts_adress', 2, 5, 1, 0, 'table', false, true);
INSERT INTO icredit.contacts_access ( id_role, table_name, field_name, page_number, group_number, group_sorting, sorting, field_view_type, visible, ro)
VALUES ( 1, 'contacts', 'localisation', 1, 1, 9, 9, 'simple', true, true);
